In [ ]:
# load libraries
import pandas as pd
import requests

In [ ]:
# Import initial unemployment data via API
# Our API is from FRED (Federal Reserve Bank of St. Louis)

key = "aa9cd57aae80525dc171dbc517b39546"

url = "https://api.stlouisfed.org/fred/series/observations"

params = {
    "series_id": "NYICLAIMS",
    "api_key": key,
    "file_type": "json",
    "frequency": "w",
    # observation_start: (when we want to change the start time)
}

fred_initial_response = requests.get(url, params=params)
fred_initial_data = fred_initial_response.json()

In [4]:
# Creating Initial FRED Dataframe

fred_initial_df = pd.DataFrame(fred_initial_data["observations"])
fred_initial_df

     realtime_start realtime_end        date  value
0        2026-02-14   2026-02-14  1986-02-15  20647
1        2026-02-14   2026-02-14  1986-02-22  21499
2        2026-02-14   2026-02-14  1986-03-01  21738
3        2026-02-14   2026-02-14  1986-03-08  22049
4        2026-02-14   2026-02-14  1986-03-15  20144
...             ...          ...         ...    ...
2082     2026-02-14   2026-02-14  2026-01-10  28142
2083     2026-02-14   2026-02-14  2026-01-17  18678
2084     2026-02-14   2026-02-14  2026-01-24  20417
2085     2026-02-14   2026-02-14  2026-01-31  23558
2086     2026-02-14   2026-02-14  2026-02-07  24382

[2087 rows x 4 columns]

In [ ]:
# Data for continued unemployment filings after the initial filing

params = {
    "series_id": "NYCCLAIMS",
    "api_key": key,
    "file_type": "json",
    "frequency": "w",
    # observation_start: (when we want to change the start time)
}
fred_continued_response = requests.get(url, params=params)
fred_continued_data = fred_continued_response.json()

In [6]:
# Creating Continued Fred Dataframe

fred_continued_df = pd.DataFrame(fred_continued_data["observations"])
fred_continued_df

     realtime_start realtime_end        date     value
0        2026-02-14   2026-02-14  1986-02-08    234789
1        2026-02-14   2026-02-14  1986-02-15    224846
2        2026-02-14   2026-02-14  1986-02-22    238566
3        2026-02-14   2026-02-14  1986-03-01    231392
4        2026-02-14   2026-02-14  1986-03-08    230848
...             ...          ...         ...       ...
2082     2026-02-14   2026-02-14  2026-01-03  219921.0
2083     2026-02-14   2026-02-14  2026-01-10  198436.0
2084     2026-02-14   2026-02-14  2026-01-17  194621.0
2085     2026-02-14   2026-02-14  2026-01-24  203505.0
2086     2026-02-14   2026-02-14  2026-01-31  215884.0

[2087 rows x 4 columns]

In [4]:
# Import NYC Eviction dataset from NYC Open Data via json

# https://data.cityofnewyork.us/City-Government/Evictions/6z8x-wfk4/about_data
eviction_data = pd.DataFrame()
url = "https://data.cityofnewyork.us/resource/6z8x-wfk4.json"
limit = 1000
offset = 0
loop = True
while loop == True:
    params = {"$limit": limit, "$offset": offset}
    r = requests.get(url, params=params)
    data = r.json()
    clean_pop = pd.json_normalize(data)
    eviction_data = pd.concat([eviction_data, clean_pop])

    if len(data) < limit:
        loop = False

    offset += limit

# View eviction data

eviction_data

KeyboardInterrupt:

In [7]:
# Import NYC Eviction dataset from NYC Open Data via json

# https://data.cityofnewyork.us/City-Government/Evictions/6z8x-wfk4/about_data
health_data = pd.DataFrame()
url = "https://data.cityofnewyork.us/resource/csut-3wpr.json"
limit = 1000
offset = 0
loop = True
while loop == True:
    params = {"$limit": limit, "$offset": offset}
    r = requests.get(url, params=params)
    data = r.json()
    clean_pop = pd.json_normalize(data)
    health_data = pd.concat([health_data, clean_pop])

    if len(data) < limit:
        loop = False

    offset += limit

# View eviction data

health_data

,prevelance,year,q_1,q_2,q_3,q_4,q_5,q_6,q_7,q_8,q_9,q_10
0,Prevalence 2020,2020,12.6,12.4,28.8,22.3,10.9,16.6,25.4,71.8,80.8,69.8
1,Lower 95% CI 2020,2020,11.6,11.4,27.5,21.0,10.0,15.5,24.0,69.5,79.6,66.1
2,Upper 95% CI 2020,2020,13.7,13.6,30.3,23.7,12.0,17.8,26.8,74.0,82.0,73.2
3,Prevalence 2019,2019,12.7,12.4,16.2,22.1,11.9,18.9,24.8,70.7,76.6,67.6
4,Lower 95% CI 2019,2019,11.6,11.3,15.0,20.8,10.8,17.6,23.4,68.4,75.2,64.2
5,Upper 95% CI 2019,2019,14.0,13.5,17.5,23.5,13.0,20.2,26.2,72.9,77.9,70.7
6,Prevalence 2018,2018,11.6,11.1,15.6,23.6,12.8,17.8,25.7,69.1,76.8,62.8
7,Lower 95% CI 2018,2018,10.6,10.2,14.6,22.4,11.8,16.7,24.5,67.0,75.6,59.7
8,Upper 95% CI 2018,2018,12.6,12.1,16.8,25.0,13.8,19.0,27.1,71.1,77.9,65.8
9,Prevalence 2017,2017,11.8,10.3,15.2,23.0,13.4,17.3,25.1,69.9,76.8,66.1
10,Lower 95% CI 2017,2017,10.9,9.5,14.2,21.8,12.5,16.2,23.9,68.0,75.7,63.4
11,Upper 95% CI 2017,2017,12.8,11.2,16.3,24.2,14.4,18.4,26.3,71.6,77.9,68.8
12,Prevalence 2016,2016,10.9,10.5,16.8,22.7,13.1,17.0,23.6,68.5,78.0,65.4
13,Lower 95% CI 2016,2016,10.0,9.7,15.7,21.5,12.2,15.9,22.5,66.5,76.8,62.4
14,Upper 95% CI 2016,2016,11.8,11.5,17.9,23.9,14.1,18.1,24.9,70.4,79.1,68.3
15,Prevalence 2015,2015,12.6,9.9,16.3,23.7,14.3,17.2,24.1,69.9,77.4,65.5
16,Lower 95% CI 2015,2015,11.7,9.1,15.2,22.5,13.3,16.1,23.0,68.1,76.3,62.7
17,Upper 95% CI 2015,2015,13.6,10.8,17.4,24.9,15.3,18.3,25.3,71.6,78.4,68.1
18,Prevalence 2014,2014,13.8,9.6,15.6,22.5,13.9,16.5,24.7,69.9,77.8,64.2
19,Lower 95% CI 2014,2014,12.8,8.7,14.5,21.2,12.8,15.4,23.4,67.8,76.6,60.7
20,Upper 95% CI 2014,2014,14.8,10.5,16.7,23.8,14.9,17.7,26.0,72.0,78.9,67.6
21,Prevalence 2013,2013,20.9,11.2,19.1,23.3,16.1,18.2,23.4,69.0,76.9,66.8
22,Lower 95% CI 2013,2013,19.7,10.3,18.0,22.1,15.0,17.0,22.2,67.0,75.7,63.7
23,Upper 95% CI 2013,2013,22.2,12.2,20.3,24.6,17.2,19.4,24.7,71.0,78.0,69.8
24,Prevalence 2012,2012,19.8,11.1,18.3,28.2,15.5,19.6,24.2,68.5,78.7,61.8
25,Lower 95% CI 2012,2012,18.5,10.1,17.0,26.7,14.4,18.2,22.8,66.3,77.5,58.5
26,Upper 95% CI 2012,2012,21.3,12.2,19.7,29.6,16.8,20.9,25.5,70.5,79.9,64.9
27,Prevalence 2011,2011,18.6,10.7,16.9,29.9,14.8,17.9,23.7,68.6,78.2,67.4
28,Lower 95% CI 2011,2011,17.0,9.6,15.5,28.2,13.5,16.4,22.2,66.2,76.7,63.9
29,Upper 95% CI 2011,2011,20.3,12.0,18.5,31.7,16.3,19.6,25.3,70.8,79.6,70.7
30,Prevalence 2010,2010,16.7,10.3,NaN,30.3,14.0,NaN,23.4,67.5,79.1,62.3
31,Lower 95% CI 2010,2010,15.4,9.4,NaN,28.8,12.9,NaN,22.1,65.4,77.8,59.4
32,Upper 95% CI 2010,2010,18.0,11.4,NaN,31.8,15.3,NaN,24.8,69.4,80.3,65.1

In [ ]:
health_data = health_data.rename(
    columns={
        "q_1": "No Health Insurance",
        "q_2": "Do not get medical care",
        "q_3": "No Personal Doctor",
        "q_4": "Drinks 1 or more sugar-sweetened beverages per day",
        "q_5": "Smoking Status (current smokers)",
        "q_6": "Obesity",
        "q_7": "Binge Drinking",
        "q_8": "Colon cancer screening, adults age 50+ (colonoscopy)",
        "q_9": "Self-reported Health Status (excellent/very good/good)",
        "q_10": "Flu shot in last 12 months, adults ages 65+ (not age-adjusted)",
    }
)

health_data

,prevelance,year,No Health Insurance,Do not get medical care,No Personal Doctor,Drinks 1 or more sugar-sweetened beverages per day,Smoking Status (current smokers),Obesity,Binge Drinking,"Colon cancer screening, adults age 50+ (colonoscopy)",Self-reported Health Status (excellent/very good/good),"Flu shot in last 12 months, adults ages 65+ (not age-adjusted)"
0,Prevalence 2020,2020,12.6,12.4,28.8,22.3,10.9,16.6,25.4,71.8,80.8,69.8
1,Lower 95% CI 2020,2020,11.6,11.4,27.5,21.0,10.0,15.5,24.0,69.5,79.6,66.1
2,Upper 95% CI 2020,2020,13.7,13.6,30.3,23.7,12.0,17.8,26.8,74.0,82.0,73.2
3,Prevalence 2019,2019,12.7,12.4,16.2,22.1,11.9,18.9,24.8,70.7,76.6,67.6
4,Lower 95% CI 2019,2019,11.6,11.3,15.0,20.8,10.8,17.6,23.4,68.4,75.2,64.2
5,Upper 95% CI 2019,2019,14.0,13.5,17.5,23.5,13.0,20.2,26.2,72.9,77.9,70.7
6,Prevalence 2018,2018,11.6,11.1,15.6,23.6,12.8,17.8,25.7,69.1,76.8,62.8
7,Lower 95% CI 2018,2018,10.6,10.2,14.6,22.4,11.8,16.7,24.5,67.0,75.6,59.7
8,Upper 95% CI 2018,2018,12.6,12.1,16.8,25.0,13.8,19.0,27.1,71.1,77.9,65.8
9,Prevalence 2017,2017,11.8,10.3,15.2,23.0,13.4,17.3,25.1,69.9,76.8,66.1
10,Lower 95% CI 2017,2017,10.9,9.5,14.2,21.8,12.5,16.2,23.9,68.0,75.7,63.4
11,Upper 95% CI 2017,2017,12.8,11.2,16.3,24.2,14.4,18.4,26.3,71.6,77.9,68.8
12,Prevalence 2016,2016,10.9,10.5,16.8,22.7,13.1,17.0,23.6,68.5,78.0,65.4
13,Lower 95% CI 2016,2016,10.0,9.7,15.7,21.5,12.2,15.9,22.5,66.5,76.8,62.4
14,Upper 95% CI 2016,2016,11.8,11.5,17.9,23.9,14.1,18.1,24.9,70.4,79.1,68.3
15,Prevalence 2015,2015,12.6,9.9,16.3,23.7,14.3,17.2,24.1,69.9,77.4,65.5
16,Lower 95% CI 2015,2015,11.7,9.1,15.2,22.5,13.3,16.1,23.0,68.1,76.3,62.7
17,Upper 95% CI 2015,2015,13.6,10.8,17.4,24.9,15.3,18.3,25.3,71.6,78.4,68.1
18,Prevalence 2014,2014,13.8,9.6,15.6,22.5,13.9,16.5,24.7,69.9,77.8,64.2
19,Lower 95% CI 2014,2014,12.8,8.7,14.5,21.2,12.8,15.4,23.4,67.8,76.6,60.7
20,Upper 95% CI 2014,2014,14.8,10.5,16.7,23.8,14.9,17.7,26.0,72.0,78.9,67.6
21,Prevalence 2013,2013,20.9,11.2,19.1,23.3,16.1,18.2,23.4,69.0,76.9,66.8
22,Lower 95% CI 2013,2013,19.7,10.3,18.0,22.1,15.0,17.0,22.2,67.0,75.7,63.7
23,Upper 95% CI 2013,2013,22.2,12.2,20.3,24.6,17.2,19.4,24.7,71.0,78.0,69.8
24,Prevalence 2012,2012,19.8,11.1,18.3,28.2,15.5,19.6,24.2,68.5,78.7,61.8
25,Lower 95% CI 2012,2012,18.5,10.1,17.0,26.7,14.4,18.2,22.8,66.3,77.5,58.5
26,Upper 95% CI 2012,2012,21.3,12.2,19.7,29.6,16.8,20.9,25.5,70.5,79.9,64.9
27,Prevalence 2011,2011,18.6,10.7,16.9,29.9,14.8,17.9,23.7,68.6,78.2,67.4
28,Lower 95% CI 2011,2011,17.0,9.6,15.5,28.2,13.5,16.4,22.2,66.2,76.7,63.9
29,Upper 95% CI 2011,2011,20.3,12.0,18.5,31.7,16.3,19.6,25.3,70.8,79.6,70.7
30,Prevalence 2010,2010,16.7,10.3,NaN,30.3,14.0,NaN,23.4,67.5,79.1,62.3
31,Lower 95% CI 2010,2010,15.4,9.4,NaN,28.8,12.9,NaN,22.1,65.4,77.8,59.4
32,Upper 95% CI 2010,2010,18.0,11.4,NaN,31.8,15.3,NaN,24.8,69.4,80.3,65.1