In [1]:
# load libraries
import pandas as pd
import requests

In [2]:
# Import initial unemployment data via API
# Our API is from FRED (Federal Reserve Bank of St. Louis)

key = "aa9cd57aae80525dc171dbc517b39546"

url = "https://api.stlouisfed.org/fred/series/observations"

params = {
    "series_id": "NYICLAIMS",
    "api_key": key,
    "file_type": "json",
    "frequency": "w",
    # observation_start: (when we want to change the start time)
}

fred_initial_response = requests.get(url, params=params)
fred_initial_data = fred_initial_response.json()

In [3]:
# Creating Initial FRED Dataframe

fred_initial_df = pd.DataFrame(fred_initial_data["observations"])
fred_initial_df["value"] = fred_initial_df["value"].astype(int)
fred_initial_df["date"] = pd.to_datetime(fred_initial_df["date"])
fred_initial_df

     realtime_start realtime_end       date  value
0        2026-03-05   2026-03-05 1986-02-15  20647
1        2026-03-05   2026-03-05 1986-02-22  21499
2        2026-03-05   2026-03-05 1986-03-01  21738
3        2026-03-05   2026-03-05 1986-03-08  22049
4        2026-03-05   2026-03-05 1986-03-15  20144
...             ...          ...        ...    ...
2084     2026-03-05   2026-03-05 2026-01-24  20417
2085     2026-03-05   2026-03-05 2026-01-31  23558
2086     2026-03-05   2026-03-05 2026-02-07  24382
2087     2026-03-05   2026-03-05 2026-02-14  16767
2088     2026-03-05   2026-03-05 2026-02-21  14073

[2089 rows x 4 columns]

In [4]:
# Data for continued unemployment filings after the initial filing

params = {
    "series_id": "NYCCLAIMS",
    "api_key": key,
    "file_type": "json",
    "frequency": "w",
    # observation_start: (when we want to change the start time)
}
fred_continued_response = requests.get(url, params=params)
fred_continued_data = fred_continued_response.json()

In [5]:
# Creating Continued Fred Dataframe

fred_continued_df = pd.DataFrame(fred_continued_data["observations"])
fred_continued_df

     realtime_start realtime_end        date     value
0        2026-03-05   2026-03-05  1986-02-08    234789
1        2026-03-05   2026-03-05  1986-02-15    224846
2        2026-03-05   2026-03-05  1986-02-22    238566
3        2026-03-05   2026-03-05  1986-03-01    231392
4        2026-03-05   2026-03-05  1986-03-08    230848
...             ...          ...         ...       ...
2084     2026-03-05   2026-03-05  2026-01-17  194621.0
2085     2026-03-05   2026-03-05  2026-01-24  203505.0
2086     2026-03-05   2026-03-05  2026-01-31  215884.0
2087     2026-03-05   2026-03-05  2026-02-07  215869.0
2088     2026-03-05   2026-03-05  2026-02-14  209519.0

[2089 rows x 4 columns]

In [ ]:
# Import NYC Eviction dataset from NYC Open Data via json

# https://data.cityofnewyork.us/City-Government/Evictions/6z8x-wfk4/about_data
eviction_data = pd.DataFrame()
url = "https://data.cityofnewyork.us/resource/6z8x-wfk4.json"
limit = 1000
offset = 0
count = 0
max_page = 4
while count != max_page:
    params = {"$limit": limit, "$offset": offset}
    r = requests.get(url, params=params)
    data = r.json()
    clean_pop = pd.json_normalize(data)
    eviction_data = pd.concat([eviction_data, clean_pop])

    if len(data) < limit:
        loop = False

    count += 1

# View eviction data

eviction_data

,court_index_number,docket_number,eviction_address,eviction_apt_num,executed_date,marshal_first_name,marshal_last_name,residential_commercial_ind,borough,eviction_zip,ejectment,eviction_possession,latitude,longitude,community_board,council_district,census_tract,bin,bbl,nta
0,327940/23A,136904,1555 UNIONPORT ROAD,2G,2025-10-15T00:00:00.000,Darlene,Barone,Residential,BRONX,10462,Not an Ejectment,Possession,40.837479,-73.858425,9,18,212,2096649,2039387501,Parkchester
1,70270/17,203634,95-14 93RD STREET 1ST FLOOR,NaN,2018-02-02T00:00:00.000,Richard,Capuano,Residential,QUEENS,11416,Not an Ejectment,Possession,40.686459,-73.848985,9,32,32,4187565,4090320010,Woodhaven
2,322487/24,038732,399 OCEAN PARKWAY,LB,2025-05-09T00:00:00.000,Gary,Rose,Residential,BROOKLYN,11218,Not an Ejectment,Possession,40.639271,-73.973319,12,39,490,3126218,3053750058,Kensington-Ocean Parkway
3,302127/25,55031,191-37 115TH AVENUE,NaN,2025-10-09T00:00:00.000,Edward,Guida,Residential,QUEENS,11412,Not an Ejectment,Possession,40.696030,-73.761274,12,27,526,4236306,4110090041,St. Albans
4,77527/18,24304,155-12 115TH DRIVE,NaN,2020-01-06T00:00:00.000,Edward,Guida,Residential,QUEENS,11434,Not an Ejectment,Possession,40.684568,-73.789713,12,28,274,4264430,4121930012,Baisley Park
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,83002/17,005692,1534 UTICA AVENUE SELF STORAGE UNIT/SP,0153,2018-03-12T00:00:00.000,Frank,Siracusa,Commercial,BROOKLYN,11234,Not an Ejectment,Eviction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,39736/18A,484504,75 EAST 190 STREET,3F,2018-12-18T00:00:00.000,Danny,Weinheim,Residential,BRONX,10468,Not an Ejectment,Possession,40.862934,-73.898255,7,14,401,2013929,2031750001,Bedford Park-Fordham North
997,B805254/16,370372,3204 PARK AVENUE,07D,2017-05-04T00:00:00.000,Richard,McCoy,Residential,BRONX,10451,Not an Ejectment,Possession,40.825206,-73.916267,3,17,141,2098307,2024099059,Morrisania-Melrose
998,336920/22,129189,1534 SELWYN AVENUE,2-L,2024-10-17T00:00:00.000,Justin,Grossman,Residential,BRONX,10457,Not an Ejectment,Possession,40.841242,-73.910388,4,16,225,2007823,2028200009,East Concourse-Concourse Village
999,327353/23,125777,1631 MULFORD AVENUE,ROOM 3,2024-09-03T00:00:00.000,Justin,Grossman,Residential,BRONX,10461,Not an Ejectment,Possession,40.844777,-73.835502,10,13,26601,2045778,2041540027,Pelham Bay-Country Club-City Island

In [3]:
eviction_data["latitude"].dtype

dtype('O')

In [ ]:
# Import NYC Health dataset from NYC Open Data via json

# https://data.cityofnewyork.us/City-Government/Evictions/6z8x-wfk4/about_data
health_data = pd.DataFrame()
url = "https://data.cityofnewyork.us/resource/csut-3wpr.json"
limit = 1000
offset = 0
loop = True
while loop:
    params = {"$limit": limit, "$offset": offset}
    r = requests.get(url, params=params)
    data = r.json()
    clean_pop = pd.json_normalize(data)
    health_data = pd.concat([health_data, clean_pop])

    if len(data) < limit:
        loop = False

    offset += limit

# View eviction data

health_data

,prevelance,year,q_1,q_2,q_3,q_4,q_5,q_6,q_7,q_8,q_9,q_10
0,Prevalence 2020,2020,12.6,12.4,28.8,22.3,10.9,16.6,25.4,71.8,80.8,69.8
1,Lower 95% CI 2020,2020,11.6,11.4,27.5,21.0,10.0,15.5,24.0,69.5,79.6,66.1
2,Upper 95% CI 2020,2020,13.7,13.6,30.3,23.7,12.0,17.8,26.8,74.0,82.0,73.2
3,Prevalence 2019,2019,12.7,12.4,16.2,22.1,11.9,18.9,24.8,70.7,76.6,67.6
4,Lower 95% CI 2019,2019,11.6,11.3,15.0,20.8,10.8,17.6,23.4,68.4,75.2,64.2
5,Upper 95% CI 2019,2019,14.0,13.5,17.5,23.5,13.0,20.2,26.2,72.9,77.9,70.7
6,Prevalence 2018,2018,11.6,11.1,15.6,23.6,12.8,17.8,25.7,69.1,76.8,62.8
7,Lower 95% CI 2018,2018,10.6,10.2,14.6,22.4,11.8,16.7,24.5,67.0,75.6,59.7
8,Upper 95% CI 2018,2018,12.6,12.1,16.8,25.0,13.8,19.0,27.1,71.1,77.9,65.8
9,Prevalence 2017,2017,11.8,10.3,15.2,23.0,13.4,17.3,25.1,69.9,76.8,66.1
10,Lower 95% CI 2017,2017,10.9,9.5,14.2,21.8,12.5,16.2,23.9,68.0,75.7,63.4
11,Upper 95% CI 2017,2017,12.8,11.2,16.3,24.2,14.4,18.4,26.3,71.6,77.9,68.8
12,Prevalence 2016,2016,10.9,10.5,16.8,22.7,13.1,17.0,23.6,68.5,78.0,65.4
13,Lower 95% CI 2016,2016,10.0,9.7,15.7,21.5,12.2,15.9,22.5,66.5,76.8,62.4
14,Upper 95% CI 2016,2016,11.8,11.5,17.9,23.9,14.1,18.1,24.9,70.4,79.1,68.3
15,Prevalence 2015,2015,12.6,9.9,16.3,23.7,14.3,17.2,24.1,69.9,77.4,65.5
16,Lower 95% CI 2015,2015,11.7,9.1,15.2,22.5,13.3,16.1,23.0,68.1,76.3,62.7
17,Upper 95% CI 2015,2015,13.6,10.8,17.4,24.9,15.3,18.3,25.3,71.6,78.4,68.1
18,Prevalence 2014,2014,13.8,9.6,15.6,22.5,13.9,16.5,24.7,69.9,77.8,64.2
19,Lower 95% CI 2014,2014,12.8,8.7,14.5,21.2,12.8,15.4,23.4,67.8,76.6,60.7
20,Upper 95% CI 2014,2014,14.8,10.5,16.7,23.8,14.9,17.7,26.0,72.0,78.9,67.6
21,Prevalence 2013,2013,20.9,11.2,19.1,23.3,16.1,18.2,23.4,69.0,76.9,66.8
22,Lower 95% CI 2013,2013,19.7,10.3,18.0,22.1,15.0,17.0,22.2,67.0,75.7,63.7
23,Upper 95% CI 2013,2013,22.2,12.2,20.3,24.6,17.2,19.4,24.7,71.0,78.0,69.8
24,Prevalence 2012,2012,19.8,11.1,18.3,28.2,15.5,19.6,24.2,68.5,78.7,61.8
25,Lower 95% CI 2012,2012,18.5,10.1,17.0,26.7,14.4,18.2,22.8,66.3,77.5,58.5
26,Upper 95% CI 2012,2012,21.3,12.2,19.7,29.6,16.8,20.9,25.5,70.5,79.9,64.9
27,Prevalence 2011,2011,18.6,10.7,16.9,29.9,14.8,17.9,23.7,68.6,78.2,67.4
28,Lower 95% CI 2011,2011,17.0,9.6,15.5,28.2,13.5,16.4,22.2,66.2,76.7,63.9
29,Upper 95% CI 2011,2011,20.3,12.0,18.5,31.7,16.3,19.6,25.3,70.8,79.6,70.7
30,Prevalence 2010,2010,16.7,10.3,NaN,30.3,14.0,NaN,23.4,67.5,79.1,62.3
31,Lower 95% CI 2010,2010,15.4,9.4,NaN,28.8,12.9,NaN,22.1,65.4,77.8,59.4
32,Upper 95% CI 2010,2010,18.0,11.4,NaN,31.8,15.3,NaN,24.8,69.4,80.3,65.1

In [22]:
health_data = health_data.rename(
    columns={
        "prevelance": "Prevelance",
        "q_1": "No Health Insurance",
        "q_2": "Do not get medical care",
        "q_3": "No Personal Doctor",
        "q_4": "Drinks 1 or more sugar-sweetened beverages per day",
        "q_5": "Smoking Status (current smokers)",
        "q_6": "Obesity",
        "q_7": "Binge Drinking",
        "q_8": "Colon cancer screening, adults age 50+ (colonoscopy)",
        "q_9": "Self-reported Health Status (excellent/very good/good)",
        "q_10": "Flu shot in last 12 months, adults ages 65+ (not age-adjusted)",
    }
)

health_data["year"] = health_data["year"].astype(int)
health_data

,Prevelance,year,No Health Insurance,Do not get medical care,No Personal Doctor,Drinks 1 or more sugar-sweetened beverages per day,Smoking Status (current smokers),Obesity,Binge Drinking,"Colon cancer screening, adults age 50+ (colonoscopy)",Self-reported Health Status (excellent/very good/good),"Flu shot in last 12 months, adults ages 65+ (not age-adjusted)"
0,Prevalence 2020,2020,12.6,12.4,28.8,22.3,10.9,16.6,25.4,71.8,80.8,69.8
1,Lower 95% CI 2020,2020,11.6,11.4,27.5,21.0,10.0,15.5,24.0,69.5,79.6,66.1
2,Upper 95% CI 2020,2020,13.7,13.6,30.3,23.7,12.0,17.8,26.8,74.0,82.0,73.2
3,Prevalence 2019,2019,12.7,12.4,16.2,22.1,11.9,18.9,24.8,70.7,76.6,67.6
4,Lower 95% CI 2019,2019,11.6,11.3,15.0,20.8,10.8,17.6,23.4,68.4,75.2,64.2
5,Upper 95% CI 2019,2019,14.0,13.5,17.5,23.5,13.0,20.2,26.2,72.9,77.9,70.7
6,Prevalence 2018,2018,11.6,11.1,15.6,23.6,12.8,17.8,25.7,69.1,76.8,62.8
7,Lower 95% CI 2018,2018,10.6,10.2,14.6,22.4,11.8,16.7,24.5,67.0,75.6,59.7
8,Upper 95% CI 2018,2018,12.6,12.1,16.8,25.0,13.8,19.0,27.1,71.1,77.9,65.8
9,Prevalence 2017,2017,11.8,10.3,15.2,23.0,13.4,17.3,25.1,69.9,76.8,66.1
10,Lower 95% CI 2017,2017,10.9,9.5,14.2,21.8,12.5,16.2,23.9,68.0,75.7,63.4
11,Upper 95% CI 2017,2017,12.8,11.2,16.3,24.2,14.4,18.4,26.3,71.6,77.9,68.8
12,Prevalence 2016,2016,10.9,10.5,16.8,22.7,13.1,17.0,23.6,68.5,78.0,65.4
13,Lower 95% CI 2016,2016,10.0,9.7,15.7,21.5,12.2,15.9,22.5,66.5,76.8,62.4
14,Upper 95% CI 2016,2016,11.8,11.5,17.9,23.9,14.1,18.1,24.9,70.4,79.1,68.3
15,Prevalence 2015,2015,12.6,9.9,16.3,23.7,14.3,17.2,24.1,69.9,77.4,65.5
16,Lower 95% CI 2015,2015,11.7,9.1,15.2,22.5,13.3,16.1,23.0,68.1,76.3,62.7
17,Upper 95% CI 2015,2015,13.6,10.8,17.4,24.9,15.3,18.3,25.3,71.6,78.4,68.1
18,Prevalence 2014,2014,13.8,9.6,15.6,22.5,13.9,16.5,24.7,69.9,77.8,64.2
19,Lower 95% CI 2014,2014,12.8,8.7,14.5,21.2,12.8,15.4,23.4,67.8,76.6,60.7
20,Upper 95% CI 2014,2014,14.8,10.5,16.7,23.8,14.9,17.7,26.0,72.0,78.9,67.6
21,Prevalence 2013,2013,20.9,11.2,19.1,23.3,16.1,18.2,23.4,69.0,76.9,66.8
22,Lower 95% CI 2013,2013,19.7,10.3,18.0,22.1,15.0,17.0,22.2,67.0,75.7,63.7
23,Upper 95% CI 2013,2013,22.2,12.2,20.3,24.6,17.2,19.4,24.7,71.0,78.0,69.8
24,Prevalence 2012,2012,19.8,11.1,18.3,28.2,15.5,19.6,24.2,68.5,78.7,61.8
25,Lower 95% CI 2012,2012,18.5,10.1,17.0,26.7,14.4,18.2,22.8,66.3,77.5,58.5
26,Upper 95% CI 2012,2012,21.3,12.2,19.7,29.6,16.8,20.9,25.5,70.5,79.9,64.9
27,Prevalence 2011,2011,18.6,10.7,16.9,29.9,14.8,17.9,23.7,68.6,78.2,67.4
28,Lower 95% CI 2011,2011,17.0,9.6,15.5,28.2,13.5,16.4,22.2,66.2,76.7,63.9
29,Upper 95% CI 2011,2011,20.3,12.0,18.5,31.7,16.3,19.6,25.3,70.8,79.6,70.7
30,Prevalence 2010,2010,16.7,10.3,NaN,30.3,14.0,NaN,23.4,67.5,79.1,62.3
31,Lower 95% CI 2010,2010,15.4,9.4,NaN,28.8,12.9,NaN,22.1,65.4,77.8,59.4
32,Upper 95% CI 2010,2010,18.0,11.4,NaN,31.8,15.3,NaN,24.8,69.4,80.3,65.1

In [10]:
def health_year_filter(data, year, metric):
    filtered = data[data["year"] == str(year)]
    filtered = filtered[filtered["Prevelance"].str.contains("Prevalence")]

    return filtered[str(metric)].iloc[0]

In [11]:
health_year_filter(health_data, 2018, "Do not get medical care")

'11.1'

In [12]:
# Test Cases

# load libraries
import pandas as pd
import requests

# Test Case 1


def health_year_fsilter(data, year, metric):
    filtered = data[data["year"] == str(year)]
    filtered = filtered[filtered["Prevelance"].str.contains("Prevalence")]

    return filtered[str(metric)].iloc[0]


# Test Case 2


def borough_count(eviction_data_clean):
    eviction_data_group = eviction_data_clean.groupby("borough").size().reset_index(name="Count")
    return eviction_data_group


# Test Case 3


def date_filter(data, column, year):
    data[str(column)] = pd.to_datetime(data[column])

    return data[data[column].dt.year == year]

In [4]:
import pandas as pd
import pandera.pandas as pa

# data to validate

fred_schema = pa.DataFrameSchema(
    {
        "value": pa.Column(int),
        "date": pa.Column(pa.DateTime, pa.Check.ge(pd.Timestamp("1968-01-01"))),
    }
)

validated_fred_intial_df = fred_schema.validate(fred_initial_df)
print(validated_fred_intial_df)

     realtime_start realtime_end       date  value
0        2026-03-05   2026-03-05 1986-02-15  20647
1        2026-03-05   2026-03-05 1986-02-22  21499
2        2026-03-05   2026-03-05 1986-03-01  21738
3        2026-03-05   2026-03-05 1986-03-08  22049
4        2026-03-05   2026-03-05 1986-03-15  20144
...             ...          ...        ...    ...
2084     2026-03-05   2026-03-05 2026-01-24  20417
2085     2026-03-05   2026-03-05 2026-01-31  23558
2086     2026-03-05   2026-03-05 2026-02-07  24382
2087     2026-03-05   2026-03-05 2026-02-14  16767
2088     2026-03-05   2026-03-05 2026-02-21  14073

[2089 rows x 4 columns]

In [28]:
eviction_schema = pa.DataFrameSchema(
    {
        "borough": pa.Column(str),
        "eviction_zip": pa.Column(int),
        "executed_date": pa.Column(pa.DateTime),
    }
)

validated_eviction_df = eviction_schema.validate(eviction_data)
print(validated_eviction_df)

    court_index_number docket_number  \
0             71444/18        082997
1           309333/22A        114501
2             39503/17        077230
3             56040/19        094517
4            71613/18A        089185
..                 ...           ...
749           60304/15        051048
750          300190/24        000420
751          314688/24        032094
752         312841/23B        116761
753           74384/16          4109

                                      eviction_address eviction_apt_num  \
0                                    580 SUTTER AVENUE               5E
1                             171-23 FOCH   BOULEV ARD        1ST FLOOR
2                                   520 CONCORD AVENUE               8A
3                                   89-19 171ST STREET               3G
4                                      240 LOTT AVENUE               6J
..                                                 ...              ...
749                           2311 SOUTHERN BOULEV ARD              402
750  92-20 50TH AVENUE APARTMENT 1B ROOM ON THE LEF...              NaN
751                                 129 PATCHEN AVENUE               6B
752                                  1338 MANOR AVENUE               3A
753                            1092 WILLMOHR ST APT C3               C3

    executed_date marshal_first_name marshal_last_name  \
0      2018-08-29             Justin          Grossman
1      2024-04-10             Justin          Grossman
2      2018-02-21              Henry             Daley
3      2019-05-22             Justin          Grossman
4      2019-01-18             Justin          Grossman
..            ...                ...               ...
749    2017-04-11             Justin          Grossman
750    2024-08-28            Richard          Pagnotta
751    2025-10-17              David             Smith
752    2025-01-09             Ileana            Rivera
753    2017-02-21             Robert          Renzulli

    residential_commercial_ind   borough  eviction_zip         ejectment  \
0                  Residential  BROOKLYN         11207  Not an Ejectment
1                  Residential    QUEENS         11434  Not an Ejectment
2                  Residential     BRONX         10455  Not an Ejectment
3                  Residential    QUEENS         11432  Not an Ejectment
4                  Residential  BROOKLYN         11212  Not an Ejectment
..                         ...       ...           ...               ...
749                Residential     BRONX         10460  Not an Ejectment
750                Residential    QUEENS         11373  Not an Ejectment
751                Residential  BROOKLYN         11221  Not an Ejectment
752                Residential     BRONX         10472  Not an Ejectment
753                Residential  BROOKLYN         11212  Not an Ejectment

    eviction_possession   latitude   longitude community_board  \
0            Possession  40.669023  -73.897531               5
1            Possession  40.686708  -73.775777              12
2            Possession  40.812399  -73.908379               1
3            Possession  40.709678  -73.789973              12
4            Possession  40.658396  -73.904629              16
..                  ...        ...         ...             ...
749          Possession  40.850963  -73.882362               6
750          Possession        NaN         NaN             NaN
751          Possession  40.687328  -73.926936               3
752          Possession  40.832494  -73.877209               9
753          Possession  40.656896  -73.917927              17

    council_district census_tract      bin         bbl  \
0                 42         1156  3342520  3037690001
1                 27          282  4463891  4123530383
2                  8           35  2120164  2025800011
3                 27          462  4209830  4098070073
4                 42          920  3326600  3036280001
..               ...          ...      ...         ...
749               15          393  2013027  2031130009
750              NaN          NaN      NaN         NaN
751               41          385  3045317  3016480006
752               18           56  2027474  2038660029
753               42          890  3102613  3046920003

                                  nta
0    East New York (Pennsylvania Ave)
1                          St. Albans
2              Mott Haven-Port Morris
3                             Jamaica
4                         Brownsville
..                                ...
749                           Belmont
750                               NaN
751                Stuyvesant Heights
752            West Farms-Bronx River
753              Rugby-Remsen Village

[123754 rows x 20 columns]

In [ ]:
health_data_schema = pa.DataFrameSchema(
    {
        "year": pa.Column(int, nullable=True),
        "No Health Insurance": pa.Column(float, nullable=True),
        "Do not get medical care": pa.Column(float, nullable=True),
        "No Personal Doctor": pa.Column(float, nullable=True),
        "Smoking Status (current smokers)": pa.Column(float, nullable=True),
        "Obesity": pa.Column(float, nullable=True),
        "Binge Drinking": pa.Column(float, nullable=True),
    }
)
cols = [
    "No Health Insurance",
    "Do not get medical care",
    "No Personal Doctor",
    "Smoking Status (current smokers)",
    "Obesity",
    "Binge Drinking",
]

health_data[cols] = health_data[cols].apply(pd.to_numeric, errors="coerce")
validated_health_data = health_data_schema.validate(health_data)
print(validated_health_data)

           Prevelance  year  No Health Insurance  Do not get medical care  \
0     Prevalence 2020  2020                 12.6                     12.4
1   Lower 95% CI 2020  2020                 11.6                     11.4
2   Upper 95% CI 2020  2020                 13.7                     13.6
3     Prevalence 2019  2019                 12.7                     12.4
4   Lower 95% CI 2019  2019                 11.6                     11.3
5   Upper 95% CI 2019  2019                 14.0                     13.5
6     Prevalence 2018  2018                 11.6                     11.1
7   Lower 95% CI 2018  2018                 10.6                     10.2
8   Upper 95% CI 2018  2018                 12.6                     12.1
9     Prevalence 2017  2017                 11.8                     10.3
10  Lower 95% CI 2017  2017                 10.9                      9.5
11  Upper 95% CI 2017  2017                 12.8                     11.2
12    Prevalence 2016  2016                 10.9                     10.5
13  Lower 95% CI 2016  2016                 10.0                      9.7
14  Upper 95% CI 2016  2016                 11.8                     11.5
15    Prevalence 2015  2015                 12.6                      9.9
16  Lower 95% CI 2015  2015                 11.7                      9.1
17  Upper 95% CI 2015  2015                 13.6                     10.8
18    Prevalence 2014  2014                 13.8                      9.6
19  Lower 95% CI 2014  2014                 12.8                      8.7
20  Upper 95% CI 2014  2014                 14.8                     10.5
21    Prevalence 2013  2013                 20.9                     11.2
22  Lower 95% CI 2013  2013                 19.7                     10.3
23  Upper 95% CI 2013  2013                 22.2                     12.2
24    Prevalence 2012  2012                 19.8                     11.1
25  Lower 95% CI 2012  2012                 18.5                     10.1
26  Upper 95% CI 2012  2012                 21.3                     12.2
27    Prevalence 2011  2011                 18.6                     10.7
28  Lower 95% CI 2011  2011                 17.0                      9.6
29  Upper 95% CI 2011  2011                 20.3                     12.0
30    Prevalence 2010  2010                 16.7                     10.3
31  Lower 95% CI 2010  2010                 15.4                      9.4
32  Upper 95% CI 2010  2010                 18.0                     11.4

    No Personal Doctor Drinks 1 or more sugar-sweetened beverages per day  \
0                 28.8                                               22.3
1                 27.5                                               21.0
2                 30.3                                               23.7
3                 16.2                                               22.1
4                 15.0                                               20.8
5                 17.5                                               23.5
6                 15.6                                               23.6
7                 14.6                                               22.4
8                 16.8                                               25.0
9                 15.2                                               23.0
10                14.2                                               21.8
11                16.3                                               24.2
12                16.8                                               22.7
13                15.7                                               21.5
14                17.9                                               23.9
15                16.3                                               23.7
16                15.2                                               22.5
17                17.4                                               24.9
18                15.6                                               22.5
19                14.5                                               21.2
20                16.7                                               23.8
21                19.1                                               23.3
22                18.0                                               22.1
23                20.3                                               24.6
24                18.3                                               28.2
25                17.0                                               26.7
26                19.7                                               29.6
27                16.9                                               29.9
28                15.5                                               28.2
29                18.5                                               31.7
30                 NaN                                               30.3
31                 NaN                                               28.8
32                 NaN                                               31.8

    Smoking Status (current smokers)  Obesity  Binge Drinking  \
0                               10.9     16.6            25.4
1                               10.0     15.5            24.0
2                               12.0     17.8            26.8
3                               11.9     18.9            24.8
4                               10.8     17.6            23.4
5                               13.0     20.2            26.2
6                               12.8     17.8            25.7
7                               11.8     16.7            24.5
8                               13.8     19.0            27.1
9                               13.4     17.3            25.1
10                              12.5     16.2            23.9
11                              14.4     18.4            26.3
12                              13.1     17.0            23.6
13                              12.2     15.9            22.5
14                              14.1     18.1            24.9
15                              14.3     17.2            24.1
16                              13.3     16.1            23.0
17                              15.3     18.3            25.3
18                              13.9     16.5            24.7
19                              12.8     15.4            23.4
20                              14.9     17.7            26.0
21                              16.1     18.2            23.4
22                              15.0     17.0            22.2
23                              17.2     19.4            24.7
24                              15.5     19.6            24.2
25                              14.4     18.2            22.8
26                              16.8     20.9            25.5
27                              14.8     17.9            23.7
28                              13.5     16.4            22.2
29                              16.3     19.6            25.3
30                              14.0      NaN            23.4
31                              12.9      NaN            22.1
32                              15.3      NaN            24.8

   Colon cancer screening, adults age 50+ (colonoscopy)  \
0                                                71.8
1                                                69.5
2                                                74.0
3                                                70.7
4                                                68.4
5                                                72.9
6                                                69.1
7                                                67.0
8                                                71.1
9                                                69.9
10                                               68.0
11                                               71.6
12                                               68.5
13                                               66.5
14                                               70.4
15                                               69.9
16                                               68.1
17                                               71.6
18                                               69.9
19                                               67.8
20                                               72.0
21                                               69.0
22                                               67.0
23                                               71.0
24                                               68.5
25                                               66.3
26                                               70.5
27                                               68.6
28                                               66.2
29                                               70.8
30                                               67.5
31                                               65.4
32                                               69.4

   Self-reported Health Status (excellent/very good/good)  \
0                                                80.8
1                                                79.6
2                                                82.0
3                                                76.6
4                                                75.2
5                                                77.9
6                                                76.8
7                                                75.6
8                                                77.9
9                                                76.8
10                                               75.7
11                                               77.9
12                                               78.0
13                                               76.8
14                                               79.1
15                                               77.4
16                                               76.3
17                                               78.4
18                                               77.8
19                                               76.6
20                                               78.9
21                                               76.9
22                                               75.7
23                                               78.0
24                                               78.7
25                                               77.5
26                                               79.9
27                                               78.2
28                                               76.7
29                                               79.6
30                                               79.1
31                                               77.8
32                                               80.3

   Flu shot in last 12 months, adults ages 65+ (not age-adjusted)
0                                                69.8
1                                                66.1
2                                                73.2
3                                                67.6
4                                                64.2
5                                                70.7
6                                                62.8
7                                                59.7
8                                                65.8
9                                                66.1
10                                               63.4
11                                               68.8
12                                               65.4
13                                               62.4
14                                               68.3
15                                               65.5
16                                               62.7
17                                               68.1
18                                               64.2
19                                               60.7
20                                               67.6
21                                               66.8
22                                               63.7
23                                               69.8
24                                               61.8
25                                               58.5
26                                               64.9
27                                               67.4
28                                               63.9
29                                               70.7
30                                               62.3
31                                               59.4
32                                               65.1